version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: magicdb
      MYSQL_USER: magician
      MYSQL_PASSWORD: "!tsGonn@B€M@g!c"
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"